public class localVariablesWithIdentifiersAsKeywords {
    public void someMethod() {
        String abc                  ;
        String transient            ;
        String returning            ;
        String search               ;
        String stat                 ;
        String this_month           ;
        String convertcurrency      ;
        String last_90_days         ;
        String last_month           ;
        String last_n_days          ;
        String last_week            ;
        String next_90_days         ;
        String next_month           ;
        String next_n_days          ;
        String next_week            ;
        String savepoint            ;
        String this_week            ;
        String tolabel              ;
        String tomorrow             ;
        String yesterday            ;
        String sharing              ;
        String get                  ;
        String after                ;
        String before               ;
        String first                ;
        String last                 ;
        String network              ;
        String category             ;
    }
}