public class A {
    public B field1;
    public B field2;
    public B field3 = new B();

    public A() {
        Integer a = 0;
        Integer b = 0;
        Integer c = 0;
        Integer d = 0;
    }

    public Integer m1() 
    {
        m2();
        String s1 = 'asf';
        /**
         * Some comments.
         */
         //single line comment;
    }

    public void m2()




            {}
}