public class TestClass {

    private Integer myInt {
        get;
        set;
    }
    
    public void doSomething() {
        Integer value = MY_INT + 2;

        if (value > 5) {
            return;
        }

        try {

        } catch (Exception ex) {
            
        } finally {

        }

        while(value > 0) {

        }

        for(Integer myInt2 = 0;myInt2 < 10; myInt2++) {

        }

        do {

        } while(value < 10);
    }
}