public with sharing class TESTEO {
    
    integer a;
    integer b;
    integer c;
    integer d;
    integer e;
    integer f;
    integer g;
    public integer h() {
        return 0;
    }
    integer i;
    integer j;
    private integer property {
        set{}

        get{}
    }
    integer l;
    integer m;
    String [] emailsAsArray = new String [5];
    integer o;
    integer p;
    integer q;
    
    public TESTEO() {
        
        
    }
}