public class VariablesClassMembers {
    private Integer d = 4;
    public Integer b = 2;
    protected Integer c = 3;
    public Integer a = 1;
    public void d(){}
    protected void c(){}
    private void a(){}
    void b(){}
    VariablesClassMembers(){}
    protected VariablesClassMembers(){}
    public VariablesClassMembers(){}
    private VariablesClassMembers(){}
    public class B{}
    private class C{}
    protected class A{}
    class D{}
}