/*
 * Copyright (c) Fundacion Jala. All rights reserved.
 * Licensed under the MIT license. See LICENSE file in the project root for full license information.
 */ 
package org.fundacionjala.oblivion.salesforce.filetype.wizard;

/**
 * Interface to create new file
 *
 * @author Sergio Daza
 */
import javax.swing.event.ChangeListener;
import javax.swing.event.DocumentListener;
import org.fundacionjala.oblivion.apex.utils.APIVersion;
import org.fundacionjala.oblivion.ui.wizard.AbstractVisualPanel;
import org.openide.WizardDescriptor;

public final class SalesforceVisualPanel extends AbstractVisualPanel {

    public static final String FILE_NAME = "name";
    public static final String FILE_VERSION = "api_version";
    public static final String HAS_METADATA_PARAM = "has_metadata_param";
    public static final String TITLE_PANEL_PARAM = "title_panel_param";
    private String titlePanel;

    /**
     * Creates new form newClassVisualPanel1
     */
    public SalesforceVisualPanel() {
        initComponents();
        apiVersion.setSelectedIndex(APIVersion.getAll().length - 1);
    }

    @Override
    public String getName() {
        return titlePanel;
    }

    public String getSalesforceName() {
        return apexClassName.getText().trim();
    }

    public String getApiVersion() {
        return apiVersion.getSelectedItem().toString();
    }

    @Override
    public boolean isValid(WizardDescriptor wizardDescriptor) {
        boolean isValid = true;
        String message = "";
        if (isValid && !isValidInput(getSalesforceName())) {
            isValid = false;
            message = "Name cannot be empty and cannot have white spaces.";
        } else if (isValid && !ifValidName(getSalesforceName())) {
            isValid = false;
            message = "The name contains invalid characters.";
        } 
        wizardDescriptor.setValid(isValid);
        wizardDescriptor.putProperty("WizardPanel_errorMessage", message);
        return isValid;
    }
    
    private boolean isValidInput(String input) {
        return !input.isEmpty() && !input.contains(" ");
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        apexClassName = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        apiVersion = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(SalesforceVisualPanel.class, "SalesforceVisualPanel.jPanel1.border.title"))); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(SalesforceVisualPanel.class, "SalesforceVisualPanel.jLabel1.text")); // NOI18N

        apexClassName.setText(org.openide.util.NbBundle.getMessage(SalesforceVisualPanel.class, "SalesforceVisualPanel.apexClassName.text")); // NOI18N
        apexClassName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apexClassNameActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        apiVersion.setModel(new javax.swing.DefaultComboBoxModel(APIVersion.getAllAsText()));

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(SalesforceVisualPanel.class, "SalesforceVisualPanel.jLabel2.text")); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(apiVersion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 49, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(apiVersion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(apexClassName, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(apexClassName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.getAccessibleContext().setAccessibleName(org.openide.util.NbBundle.getMessage(SalesforceVisualPanel.class, "SalesforceVisualPanel.jPanel3.AccessibleContext.accessibleName")); // NOI18N
        jPanel3.getAccessibleContext().setAccessibleParent(jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(241, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(301, Short.MAX_VALUE))
        );

        jPanel1.getAccessibleContext().setAccessibleName(org.openide.util.NbBundle.getMessage(SalesforceVisualPanel.class, "SalesforceVisualPanel.jPanel1.AccessibleContext.accessibleName")); // NOI18N
    }// </editor-fold>//GEN-END:initComponents

    private void apexClassNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apexClassNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apexClassNameActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apexClassName;
    private javax.swing.JComboBox apiVersion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables

    @Override
    protected void addDocumentListener(DocumentListener documentListener) {
        apexClassName.getDocument().addDocumentListener(documentListener);
    }

    @Override
    protected void addChangeListener(ChangeListener changeListener) {

    }

    @Override
    public void initProperties(WizardDescriptor wizardDescriptor) {
        boolean isVersionVisible = (boolean) wizardDescriptor.getProperty(HAS_METADATA_PARAM);
        titlePanel = (String) wizardDescriptor.getProperty(TITLE_PANEL_PARAM);
        jPanel3.setVisible(isVersionVisible);
    }

}
