public class enumWithKeywordsAsIdentifiers {
    public enum abc                  { value }
    public enum transient            { value }
    public enum returning            { value }
    public enum search               { value }
    public enum stat                 { value }
    public enum this_month           { value }
    public enum convertcurrency      { value }
    public enum last_90_days         { value }
    public enum last_month           { value }
    public enum last_n_days          { value }
    public enum last_week            { value }
    public enum next_90_days         { value }
    public enum next_month           { value }
    public enum next_n_days          { value }
    public enum next_week            { value }
    public enum savepoint            { value }
    public enum this_week            { value }
    public enum tolabel              { value }
    public enum tomorrow             { value }
    public enum yesterday            { value }
    public enum sharing              { value }
    public enum get                  { value }
    public enum after                { value }
    public enum before               { value }
    public enum first                { value }
    public enum last                 { value }
}